const { USER_ROLE } = constants;

router
  .post(
    "/customers/auth/signUp",
    validators.customers.signUpPayloadValidation,
    middlewares.validation.request,
    actions.customers.auth.signUp
  )
  .post(
    "/customers/auth/login",
    validators.customers.signInPayloadValidation,
    middlewares.validation.request,
    middlewares.local_passport.authenticate,
    actions.customers.auth.signIn
  )
  .post(
    "/customers/auth/verifyEmail",
    validators.customers.emailPayloadValidation,
    middlewares.validation.request,
    actions.customers.auth.verifyEmail
  )
  .get(
    "/customers/auth/usernameAvailability/:username",
    validators.customers.usernameAvailabilityValidation,
    middlewares.validation.request,
    actions.customers.auth.checkUsernameAvailability
  )

  .post(
    "/customers/auth/verify-code/:id",
    middlewares.id_validation.validateId,
    validators.customers.verifyCodePayloadValidation,
    middlewares.validation.request,
    actions.customers.auth.verifyCode
  )
  .post(
    "/customers/auth/resend-code/:id",
    validators.customers.resendCodePayloadValidation,
    middlewares.validation.request,
    actions.customers.auth.resendCode
  )
  .patch(
    "/customers/auth/forgot-password",
    validators.customers.emailPayloadValidation,
    middlewares.validation.request,
    actions.customers.auth.forgotPassword
  )
  .patch(
    "/customers/auth/reset-password/:id",
    middlewares.id_validation.validateId,
    validators.customers.resetPasswordPayload,
    middlewares.validation.request,
    actions.customers.auth.resetPassword
  )
  .patch(
    "/customers",
    middlewares.verifyUserRole(USER_ROLE.CUSTOMER),
    validators.customers.update,
    middlewares.validation.request,
    actions.customers.update.profile
  );

module.exports = { prefix: "customers", router };
