const { USER_ROLE } = constants;
router
  .post(
    "/meetings",
    middlewares.removeNullishValuesFromBody,
    validators.meetings.add,
    middlewares.validation.request,
    actions.meetings.create.meeting
  )
  .patch(
    "/meetings/:id",
    middlewares.verifyUserRole(USER_ROLE.CUSTOMER),
    actions.meetings.update
  )
  .delete(
    "/meetings/:id",
    middlewares.verifyUserRole(USER_ROLE.CUSTOMER),
    actions.meetings.delete
  )
  .get(
    "/meetings",
    validators.meetings.getList,
    middlewares.validation.request,
    actions.meetings.get.list
  )
  .get(
    "/meetings/vendors/:id",
    middlewares.verifyUserRole(USER_ROLE.ADMIN),
    validators.meetings.getList,
    validators.common.getById,
    middlewares.validation.request,
    actions.meetings.get.listByVendorId
  )
  .get(
    "/meetings/customers/:id",
    middlewares.verifyUserRole(USER_ROLE.ADMIN),
    validators.meetings.getList,
    validators.common.getById,
    middlewares.validation.request,
    actions.meetings.get.listByCustomerId
  )
  .get(
    "/meetings/:id",
    validators.meetings.getById,
    middlewares.validation.request,
    actions.meetings.get.byId
  );

module.exports = { prefix: "meeting", router };
